"""sRGB/D65 colorimetric references and pinned HueBLE API with mocked BLE only."""
import asyncio
import math
import struct
import unittest
from types import SimpleNamespace as NS
from unittest.mock import AsyncMock,patch
import hue_driver as hd

# Independent sRGB/D65 reference chromaticities, not generated by the helper.
CASES = {
    'pink': ((255,105,180),(.400424102011,.254533185504)),
    'red': ((255,0,0),(.64,.33)),
    'green': ((0,255,0),(.30,.60)),
    'blue': ((0,0,255),(.15,.06)),
    'cyan': ((0,255,255),(.224655633125,.328760259206)),
    'magenta': ((255,0,255),(.320937741119,.154190221199)),
    'yellow': ((255,255,0),(.419320092998,.505245826920)),
    'white': ((255,255,255),(.312726604392,.329023152403)),
}


class ColorConversionTests(unittest.TestCase):
    def test_reference_srgb_colors_including_requested_pink(self):
        for name,(rgb,expected) in CASES.items():
            with self.subTest(color=name):
                actual=hd.rgb_to_xy(rgb)
                for got,want in zip(actual,expected):self.assertAlmostEqual(got,want,places=6)
    def test_inverse_srgb_recovers_pink_without_channel_swap_or_double_gamma(self):
        for rgb in ((255,105,180),(10,51,77),(11,105,180),(25,25,25)):
            x,y=hd.rgb_to_xy(rgb);X=x/y;Y=1.;Z=(1-x-y)/y
            # Inverse standard sRGB/D65 matrix, independent of the production helper.
            linear=(3.2404542*X-1.5371385*Y-.4985314*Z,
                    -.9692660*X+1.8760108*Y+.0415560*Z,
                    .0556434*X-.2040259*Y+1.0572252*Z)
            supplied=[c/255 for c in rgb]
            expected=[c/12.92 if c<=.04045 else ((c+.055)/1.055)**2.4 for c in supplied]
            for got,want in zip(linear,expected):self.assertAlmostEqual(got/max(linear),want/max(expected),places=6)
    def test_neutral_white_does_not_shift_with_intensity(self):
        white=hd.rgb_to_xy((255,255,255))
        for value in (1,10,11,64,128,254):
            for got,want in zip(hd.rgb_to_xy((value,)*3),white):self.assertAlmostEqual(got,want,places=12)
    def test_existing_clamp_black_behavior_and_finite_coordinates(self):
        self.assertEqual(hd.rgb_to_xy((0,0,0)),(.3127,.3290))
        self.assertEqual(hd.rgb_to_xy((500,-10,0)),hd.rgb_to_xy((255,0,0)))
        for rgb,_ in CASES.values():
            x,y=hd.rgb_to_xy(rgb);self.assertTrue(math.isfinite(x) and math.isfinite(y));self.assertGreater(y,0);self.assertLessEqual(x+y,1)


class HueColorApiTests(unittest.IsolatedAsyncioTestCase):
    @classmethod
    def setUpClass(cls):
        from PySide6.QtWidgets import QApplication
        cls.app=QApplication.instance() or QApplication([])

    async def test_driver_api_xy_calls_not_hs_and_separate_brightness(self):
        driver=hd.HueDriver({},lambda *args:None)
        light=NS(connected=True,set_colour_xy=AsyncMock(),set_brightness=AsyncMock(),set_colour_temp=AsyncMock())
        driver.light=light;driver.capabilities.update(color=True,brightness=True)
        for name,(rgb,expected) in CASES.items():
            with self.subTest(color=name):
                await driver.write('color',rgb)
                actual=light.set_colour_xy.call_args.args
                for got,want in zip(actual,expected):self.assertAlmostEqual(got,want,places=6)
        await driver.write('brightness',100)
        self.assertEqual(light.set_colour_xy.await_count,len(CASES));light.set_brightness.assert_awaited_once_with(100)
        light.set_colour_temp.assert_not_awaited()

    async def test_real_hueble_xy_payload_and_mock_readback_for_all_reference_colors(self):
        import HueBLE as hue
        light=hd.managed_light_class()(NS(name='Test bulb',address='MOCK',details=None))
        writes=[]
        async def write(uuid,payload):writes.append((uuid,payload))
        # Keep real HueBLE float conversion/packing/read decoding, mock GATT only.
        with patch.object(light,'_write_gatt',side_effect=write),patch.object(light,'_read_gatt',new=AsyncMock()) as read:
            for name,(rgb,expected) in CASES.items():
                with self.subTest(color=name):
                    await light.set_colour_xy(*hd.rgb_to_xy(rgb))
                    uuid,payload=writes[-1];self.assertEqual(uuid,hue.UUID_XY_COLOUR)
                    expected_payload=struct.pack('<HH',int(expected[0]*65535),int(expected[1]*65535))
                    self.assertEqual(payload,expected_payload)
                    read.return_value=payload
                    observed=await light.poll_colour_xy()
                    for got,want in zip(observed,expected):self.assertLessEqual(abs(got-want),1/65535)
        self.assertEqual(len(writes),len(CASES))

    async def test_original_and_studio_preserve_same_manual_rgb_before_shared_conversion(self):
        from studio_qt.dual_adapter import DualLightingAdapter
        from studio_qt.controller import StudioController
        for name,(rgb,_) in CASES.items():
            with self.subTest(color=name):
                original=hd.HueService({},dict(power=True,brightness=128,mode='color',temperature=300,rgb=rgb))
                adapter=DualLightingAdapter(hue_identity={'name':'Mock bulb'})
                try:
                    adapter.hue_connected=True;adapter.hue_caps={'color':True,'brightness':True,'power':True}
                    adapter.hue.wanted=True
                    c=StudioController(state=adapter.state,adapter=adapter);c.select_channel('Hue')
                    c.set_hex('#'+''.join(f'{v:02X}' for v in rgb))
                    self.assertEqual(original.desired()['color'],rgb);self.assertEqual(adapter.hue.pending['color'],rgb)
                    self.assertNotIn('temperature',adapter.hue.pending)
                finally:adapter.close()
